In [2]:
import pandas as pd
import json

In [70]:
done = ["EAR", "EYE", "FACE", 
        "HEAD", "HEARING", "MIND", 
        "NOSE", "VERTIGO", "VISION", 
        "MOUTH", "TEETH", "THROAT", "EXTERNAL THROAT",
        "STOMACH", "ABDOMEN", "RECTUM", "STOOL", "BLADDER",
        "KIDNEYS", "PROSTATE GLAND", "URETHRA", "URINE",
        "GENITALIA-MALE", "GENITALIA-FEMALE", "LARYNX AND TRACHEA",
        "RESPIRATION", "COUGH"
        ]

In [72]:
def get_num_queries_chapter():
    rows = []
    for chapter_name in done:
        f = open(f"data/chapter_{chapter_name}.json", "r")
        j_data = json.loads(f.read())
        f.close()
        num_queries = 0
        for row_ in j_data["data"]:
            if row_["RemediesCount"] > 0:
                num_queries += 1
        rows.append({"chapter": chapter_name, "queries": num_queries})
    
    return pd.DataFrame(rows)

In [73]:
get_num_queries_chapter()

               chapter  queries
0                  EAR     1890
1                  EYE     1661
2                 FACE     2016
3                 HEAD     6334
4              HEARING      151
5                 MIND     4902
6                 NOSE     1475
7              VERTIGO      433
8               VISION      808
9                MOUTH     1537
10               TEETH      759
11              THROAT     1017
12     EXTERNAL THROAT      262
13             STOMACH     2802
14             ABDOMEN     3312
15              RECTUM     1244
16               STOOL      222
17             BLADDER      712
18             KIDNEYS      257
19      PROSTATE GLAND       92
20             URETHRA      549
21               URINE      386
22      GENITALIA-MALE     1063
23    GENITALIA-FEMALE     1403
24  LARYNX AND TRACHEA      658
25         RESPIRATION      707
26               COUGH      173

In [74]:
from pathlib import Path

def get_count_missing_remedies():
    rows = []
    for chapter_name in done:
        f = open(f"data/chapter_{chapter_name}.json", "r")
        j_data = json.loads(f.read())
        f.close()
        symptoms = set()
        for row_ in j_data["data"]:
            if row_["RemediesCount"] > 0:
                assert(row_["SymptomId"] not in symptoms)
                symptoms.add(row_["SymptomId"])
        
        remedies = set()
        
        if Path(f"data/remedies/chapter_{chapter_name}.json").exists():
            f = open(f"data/remedies/chapter_{chapter_name}.json", "r")
            j_data = json.loads(f.read())
            f.close()
            
            for row_ in j_data["data"]:         
                assert(row_["symptom_"]["SymptomId"] not in remedies)
                if row_["RemediesLocal"] > 0:
                    remedies.add(row_["symptom_"]["SymptomId"])
            assert remedies.issubset(symptoms)
        
        rows.append({"chapter": chapter_name, "n_missing": len(symptoms-remedies), "total": len(symptoms), "done": len(remedies)})
    
    return pd.DataFrame(rows)

In [75]:
get_count_missing_remedies()

               chapter  n_missing  total  done
0                  EAR       1890   1890     0
1                  EYE       1661   1661     0
2                 FACE       2016   2016     0
3                 HEAD       6334   6334     0
4              HEARING        151    151     0
5                 MIND       4602   4902   300
6                 NOSE       1475   1475     0
7              VERTIGO        142    433   291
8               VISION        808    808     0
9                MOUTH       1537   1537     0
10               TEETH        759    759     0
11              THROAT       1017   1017     0
12     EXTERNAL THROAT        262    262     0
13             STOMACH       2802   2802     0
14             ABDOMEN       3312   3312     0
15              RECTUM       1244   1244     0
16               STOOL        222    222     0
17             BLADDER        712    712     0
18             KIDNEYS        257    257     0
19      PROSTATE GLAND         92     92     0
20             URETHRA        549    549     0
21               URINE        386    386     0
22      GENITALIA-MALE       1063   1063     0
23    GENITALIA-FEMALE       1403   1403     0
24  LARYNX AND TRACHEA        658    658     0
25         RESPIRATION        707    707     0
26               COUGH        173    173     0

In [62]:
433+808+140

1381

In [63]:
433 - 142

291